### PR TITLE
Version 0.7.2

### PR DESCRIPTION
**Pull request by kemalkongar**
Bug fix in error messages for unknown note values.

### CODE REVIEW

**Review by raviraina — APPROVED** [review]

**Review by raviraina — CHANGES_REQUESTED** [review]
git_actions looks like it will overwrite the checks on main

**Review by GabbyHalpin — CHANGES_REQUESTED** [review]
review the gti_actions

**Review by GabbyHalpin — APPROVED** [review]
All changes are good no issues

**Review by raviraina — APPROVED** [review]

**Comment by napulen** [comment]
Are we pushing to PyPI now? It seems like latest is still `0.7.0`: https://pypi.org/project/mei2volpiano/

**Comment by raviraina** [comment]
@napulen We are currently trying to automate the publishing process

**Comment by GabbyHalpin** [comment]
Yeah were currently working not that but running into some interesting errors

**Pull request merged**
