### PR TITLE
Less scrolling on the single-character strings of the tests.

### PR DESCRIPTION
**Pull request by napulen**
This works only for lists with single-character strings. Interpreting a string as an iterable (list).

All tests pass on my end and new strings are equivalent to the original ones.

### CODE REVIEW

**Review by kemalkongar — APPROVED** [review]
Tested with pytest locally, it checks out.

**Comment by deepio** [comment]
github action pytest?

**Comment by napulen** [comment]
Drafted. One more commit coming.

**Comment by napulen** [comment]
I'm good now. 

`pytest` is OK locally for all tests.

**Comment by napulen** [comment]
> github action pytest?

There is no `.github/workflows` yet.  That should be the next PR.

**Review by deepio — APPROVED** [review]

**Pull request merged**
